version: '3.9'

services:
  postgres:
    image: postgres:16-alpine
    container_name: sevenss_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: sevenss
      POSTGRES_USER: sevenss_user
      POSTGRES_PASSWORD: sevenssGBR5
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/migrate.sql:/docker-entrypoint-initdb.d/01-migrate.sql
volumes:
  postgres_data:
  #minio_data:
